### ISSUE TITLE
Old nixpkgs version is fixed in default.nix

### ISSUE THREAD

**Issue by mpoquet** [freuk/datamovepkgs#1]
Hello,

An old nixpkgs version (17.09) is fixed in [default.nix](https://github.com/freuk/datamovepkgs/blob/master/default.nix#L3).

This can be annoying for users, as they may end up with multiple versions of the packages depending on which nixpkgs they use. For exemple I end up with full 17.09-build packages when I directly use datamovepkgs, while I end up with 18.03-built packages when I use the packages from the outside.

Should we update this fixed version?

**Comment by freuk** [comment]
What does 'from the outside' mean?
simply don't inherit the 'pkgs' arguments, or do, depending on your needs.

BTW ideally we should provide a real pinning
(https://nixos.wiki/wiki/FAQ/Pinning_Nixpkgs) with whatever version
works. Will PR

Quoting Millian Poquet (2018-07-16 14:48:57)

**Comment by mpoquet** [comment]
By "from the outside" I meant "when inheriting a pkgs that is different from 17.03".

PR seems great, thanks!

**Comment by freuk** [comment]
that is standard behavior imo, how would you have it?

Quoting Millian Poquet (2018-07-16 18:34:46)
